radar(ci-cd): moves GHA to adopt and other CI-CD to hold
Jimdo/build-your-own-radar pull request #29
Opened 2022-01-26 15:15 UTC by Gio-Jimdo

Travis CI an Circle CI should no longer be used. All existing uses should migrate to GitHub Actions.

2022-01-26 15:21 UTC, pezhman32 commented
@Gio-Jimdo while viewing the file, github complains:
```
We can make this file beautiful and searchable if this error is corrected: It looks like row 5 should actually have 6 columns, instead of 5. in line 4.
```

2022-01-26 15:23 UTC, oerd commented
> @Gio-Jimdo while viewing the file, github complains:
> 
> ```
> We can make this file beautiful and searchable if this error is corrected: It looks like row 5 should actually have 6 columns, instead of 5. in line 4.
> ```

@Gio-Jimdo added the `url` field, all existing fields require a trailing `,` to match the field number

2022-01-26 15:28 UTC, bijancn commented
For future reference: this is the corresponding adoption task https://jimplan.atlassian.net/wiki/x/DgB-sg

2022-01-26 15:35 UTC, cmuelhau requested changes

2022-01-26 15:35 UTC, cmuelhau commented on data/backend.csv
> +name,ring,quadrant,isNew,description,url
the addition of `url` seems to break the nice table view in github. Most likely, you'd have to add an empty column for all other entries

2022-01-26 16:11 UTC, Gio-Jimdo commented on data/backend.csv
> +name,ring,quadrant,isNew,description,url
Yup, I fell into the very trap I mentioned of ensuring the CSV is rendering before you PR. This convo has validated my expectation that we'd catch even formatting issues thru this process. I'll fix that now.

2022-01-27 09:19 UTC, cmuelhau approved these changes

2022-01-28 09:02 UTC, merged